name: deployNote

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install and run docsify-cli
        run: |
           npm install -g docsify-cli
           rm ./_sidebar.md
           docsify generate .

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'solidSpoon'
          author_email: 'solidSpoon.outlook.com'
          message: 'Update _sidebar.md by github actions'
          push: true