name: deployNote

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install and run docsify-cli
        run: |
           npm install -g docsify-cli
           rm ./_sidebar.md
           docsify generate .
           git add _sidebar.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update _sidebar.md by github actions'
          title: 'Update _sidebar.md'
          body: 'This PR was automatically created by GitHub Actions.'
          branch: 'update-sidebar'